version: '2.1'
services:
  airflow:
    build: .
    restart: always
    container_name: airflow
    volumes:
      - ./airflow.cfg:/opt/airflow/airflow.cfg
      - ../airflow-pipelines/dags:/opt/airflow/dags
      - ${MY_AIRFLOW_SERVICE_ACCOUNT}:${GOOGLE_APPLICATION_CREDENTIALS}
    ports:
      - 8080:8080
    env_file:
      - ../variables.env
      - ../secrets.env
    healthcheck:
      test: [ "CMD", "nc", "-z", "airflow", "8080" ]
      timeout: 45s
      interval: 10s
      retries: 10
