FROM apache/airflow:2.2.3
RUN pip install apache-airflow-providers-slack==4.0.1 && \
    pip install apache-airflow-providers-http==2.0.1 && \
    pip install apache-airflow-providers-google==6.2.0 && \
    pip install apache-airflow-providers-postgres==2.4.0 && \
    pip install pandas==1.3.5 && \
    pip install fsspec=2021.11.1 && \
    pip install gcsfs
